remote_theme: pages-themes/cayman@v0.2.0
title: "Ariel Ben Avi"
name: "Ariel Ben Avi"
subtitle: "CS-Math @ Columbia | Software Engineer"
description: "Software Engineer, Quant, and Cybersecurity Enthusiast"
twitter: "#"
linkedin: "#"
github: "#"
